name: codespell

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630 # v2.2
        with:
          # AKIA prefixes look like words; allow them. "sts" too.
          ignore_words_list: AKIA,sts,fo,nd
          check_filenames: true
          check_hidden: true
          skip: ./.git,./LICENSE
